// Generated by delombok at Sat Feb 08 23:15:03 CET 2014
/*
 * Copyright 2012, 2013 Martijn van de Rijdt 
 * 
 * This file is part of the Ultimate Marvel vs Capcom 3 Replay Manager.
 * 
 * The Ultimate Marvel vs Capcom 3 Replay Manager is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * The Ultimate Marvel vs Capcom 3 Replay Manager is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with the Ultimate Marvel vs Capcom 3
 * Replay Manager. If not, see <http://www.gnu.org/licenses/>.
 */
package nl.mvdr.umvc3replayanalyser.model.predicate;

import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;

import nl.mvdr.umvc3replayanalyser.model.AssistType;
import nl.mvdr.umvc3replayanalyser.model.Team;
import nl.mvdr.umvc3replayanalyser.model.Umvc3Character;

/**
 * Predicate for matching a team.
 *
 * @author Martijn van de Rijdt
 */
public class MatchTeamPredicate implements Predicate<Team> {

    /**
     * Characters.
     */
    private final List<Umvc3Character> characters;

    /**
     * Assist types.
     */
    private final List<AssistType> assists;

    /**
     * Whether character order needs to be respected when matching against a team.
     */
    private final boolean maintainCharacterOrder;

    /**
     * Constructor.
     *
     * @param character1
     *            character 1
     * @param assist1
     *            assist type for character 1
     * @param character2
     *            character 2
     * @param assist2
     *            assist type for character 2
     * @param character3
     *            character 3
     * @param assist3
     *            assist type for character 3
     * @param maintainCharacterOrder
     *            whether character order needs to be respected when matching against a team
     */
    public MatchTeamPredicate(Umvc3Character character1, AssistType assist1, Umvc3Character character2,
            AssistType assist2, Umvc3Character character3, AssistType assist3, boolean maintainCharacterOrder) {
        this.characters = Arrays.asList(character1, character2, character3);
        this.assists = Arrays.asList(assist1, assist2, assist3);
        this.maintainCharacterOrder = maintainCharacterOrder;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean test(Team team) {
        boolean result = true;
        int i = 0;
        while (result && i != 3) {
            Umvc3Character character = characters.get(i);
            if (character != null) {
                AssistType assist = assists.get(i);
                if (maintainCharacterOrder) {
                    result = character == team.getCharacters().get(i);
                    result = result && (assist == null || assist == team.getAssists().get(i));
                } else {
                    int characterIndex = team.getCharacters().indexOf(character);
                    result = 0 <= characterIndex;
                    result = result && (assist == null || assist == team.getAssists().get(characterIndex));
                }
            }
            i++;
        }
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "MatchTeamPredicate(characters=" + this.characters + ", assists=" + this.assists
                + ", maintainCharacterOrder=" + this.maintainCharacterOrder + ")";
    }
}